apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app_namespace }}
  labels:
    app: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
      - image: {{ .Values.repository }}:{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.app_name }}
        imagePullPolicy: Always
        env:          
          {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote}}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
