repository: ''
version: 'latest'
app_name: 'nginx'
app_namespace: default
replicas: 1

resources:
  limits:
    cpu: '500m'
    memory: '1G'
  requests:
    cpu: '500m'
    memory: '1G'

env:
  - name: NODE_ENV
    value: test
        
ingress:
  main_domain: 'api.test.nginx'
  additional_domain: 'api.test.nginx'
  port: 80
