on:
  release:
    types: [deleted]

name: Nginx test rollback

jobs:
  rollback:
    name: Kubernetes prepared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          mv ./.helm/app/Chart.yaml ./.helm/app/Chart.old.yaml &&
          cat ./.helm/app/Chart.old.yaml | grep -v appVersion > ./.helm/app/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./.helm/app/Chart.yaml &&
          cat ./.helm/app/Chart.yaml
        
      - name: Delete release
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm delete nginx-test --namespace=default
          kubeconfig: '${{ secrets.KUBECONFIG }}'
